# Generated by Django 3.2.14 on 2022-08-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='автор')),
                ('text', models.TextField(blank=True, null=True, verbose_name='сообщение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('type_message', models.CharField(choices=[('0', 'Пользовательское сообщение'), ('1', 'На модерацию'), ('2', 'Ответ модератора'), ('3', 'Модератору')], default='0', max_length=1, verbose_name='Тип сообщения')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('to_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='адресат(группа)')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
