# Generated by Django 4.0.6 on 2022-08-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_message_to_group_alter_message_from_user_and_more'),
        ('adminapp', '0002_message_to_user'),
    ]

    operations = [
    ]
