# Generated by Django 3.2.8 on 2022-07-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateTimeField(null=False, blank=False, auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='update_date',
            field=models.DateTimeField(null=False, blank=False, auto_now=True, verbose_name='дата обновления'),
        ),
    ]
