# Generated by Django 3.2.14 on 2022-08-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220801_1528'),
        ('mainapp', '0002_auto_20220801_2109'),
    ]

    operations = [
    ]
