# Generated by Django 3.2.8 on 2022-08-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
        ('mainapp', '0002_auto_20220801_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogs', verbose_name='блог'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(blank=True, max_length=30, verbose_name='тег'),
        ),
    ]
